let newsletterDetails =
[{"displayName":"Midday News Update","newsletterName":"midday_news_update","newsletterCopy":"A daily newsletter with midday's top stories."},
    {"displayName":"Afternoon News Update","newsletterName":"afternoon_news_update","newsletterCopy":"A daily newsletter with the afternoon's top stories."},
    {"displayName":"Breaking News Email","newsletterName":"breaking_news_email","newsletterCopy":"Breaking news updates from the Democrat-Gazette."},
    {"displayName":"Politics","newsletterName":"politics","newsletterCopy":"A daily newsletter on politics in Arkansas and across the U.S."},
    {"displayName":"Sports Email","newsletterName":"sports_email","newsletterCopy":"A daily newsletter on sports."},
    {"displayName":"Editorial","newsletterName":"editorial","newsletterCopy":"A daily newsletter of opinion pieces."},
    {"displayName":"Crime Email","newsletterName":"crime_email","newsletterCopy":"A daily newsletter on crime in Arkansas."},
    {"displayName":"Week In Little Rock","newsletterName":"week_in_little_rock","newsletterCopy":"A weekly update on news in Little Rock."},
    {"displayName":"Week In North Little Rock","newsletterName":"week_in_north_little_rock","newsletterCopy":"A weekly update on news in North Little Rock."},
    {"displayName":"Business email","newsletterName":"business_email","newsletterCopy":"A weekly update on business in Arkansas."},
    {"displayName":"Arkansas weekend email","newsletterName":"arkansas_weekend_email","newsletterCopy":"A weekly newsletter on weekend events in Central Arkansas."},
    {"displayName":"Restaurants eblast","newsletterName":"restaurants_eblast","newsletterCopy":"A weekly newsletter on food in Arkansas."},
    {"displayName":"Plan it Janet","newsletterName":"plan_it_janet","newsletterCopy":"A weekly newsletter from master gardener Janet Carson."},
    {"displayName":"Pine Bluff news","newsletterName":"pine_bluff_news","newsletterCopy":"A daily update on news in Pine Bluff."},
    {"displayName":"The Article Newsletter","newsletterName":"the_article_newsletter","newsletterCopy":""},
    {"displayName":"Complimentary article","newsletterName":"complimentary_article","newsletterCopy":""},
    {"displayName":"Morning News Update - A","newsletterName":"morning_news_update_-_a","newsletterCopy":""},
    {"displayName":"Obituaries","newsletterName":"obituaries","newsletterCopy":""},
    {"displayName":"Obituaries Alert","newsletterName":"obituaries_alert","newsletterCopy":""},
    {"displayName":"River Valley","newsletterName":"river_valley","newsletterCopy":""},
    {"displayName":"Grade Point Arkansas","newsletterName":"grade_point_arkansas","newsletterCopy":"A weekly update on education in Arkansas."},
    {"displayName":"High Profile Email","newsletterName":"high_profile_email","newsletterCopy":"A weekly collection of stories from the High Profile section."}]